build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22
labels:
  org.opencontainers.image.title: CCTV Event Timeline
  org.opencontainers.image.description: Local Hikvision historical event timeline
  org.opencontainers.image.source: https://github.com/xerxel/NVR-Add-On

